version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  NERT Server:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mongo:4.0.3
    working_directory: ~/WEEK-11-TASK
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-server-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-server-
      - run: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-server-{{ checksum "package.json" }}
          paths:
            # Save the yarn cache folder so we can cache cypress as well.
            - ~/.cache
      # Run typescript
      - run: yarn tsc
      # run tests!
      - run: yarn test:unit
workflows:
  node-tests:
    jobs:
      - NERT Server
